version: '3'
services:
  app:
    build:
      context: ./project
    ports:
      - "8080:8080"
    networks:
      - eco4marseille

  

volumes:
  my-db:
networks:
  eco4marseille:
    driver: bridge
